In [2]:
# working wih python module

In [3]:
import numpy

In [5]:
!python -m pip install numpy

You should consider upgrading via the 'c:\Python310\python.exe -m pip install --upgrade pip' command.


In [6]:
import numpy

In [7]:
import my_file

In [8]:
my_file.abc()

Hello World


In [9]:
import newpack

In [10]:
newpack.new1.abc()

AttributeError: module 'newpack' has no attribute 'new1'

In [11]:
import newpack.new1"

SyntaxError: unterminated string literal (detected at line 1) (856016910.py, line 1)

In [12]:
import newpack.new1

In [13]:
newpack.new1.abc()

AttributeError: module 'newpack.new1' has no attribute 'abc'

In [14]:
import newpack.new1

In [17]:
newpack.new1.abc()

AttributeError: module 'newpack.new1' has no attribute 'abc'

In [18]:
newpack.new1.abc()

AttributeError: module 'newpack.new1' has no attribute 'abc'

In [19]:
newpack.new1.abc

AttributeError: module 'newpack.new1' has no attribute 'abc'

In [20]:
from newpack import abc

ImportError: cannot import name 'abc' from 'newpack' (unknown location)

In [21]:
import newpack

In [22]:
import newpack.new1

In [23]:
newpack.new1.abc()

AttributeError: module 'newpack.new1' has no attribute 'abc'

In [25]:
import numpy as np

In [26]:
a=np.array([])
a

array([], dtype=float64)

In [27]:
b=np.array([2,3,5,67])
b

array([ 2,  3,  5, 67])

In [28]:
len(a)

0

In [29]:
len(b)

4

In [30]:
a.dtype

dtype('float64')

In [31]:
b.dtype

dtype('int32')

In [32]:
b.shape

(4,)

In [33]:
b.size

4

In [34]:
a.shape

(0,)

In [35]:
a.ndim

1

In [36]:
b.ndim

1

In [37]:
type(a)

numpy.ndarray

In [38]:
c=np.array([[2,3,4],[3,6,8],[10,11,9],[12,32,11]])

In [39]:
c

array([[ 2,  3,  4],
       [ 3,  6,  8],
       [10, 11,  9],
       [12, 32, 11]])

In [40]:
c.shape

(4, 3)

In [41]:
c.ndim

2

In [45]:
# /4*3*2
d=np.array([[[2,2],[3,4],[4,5]],[[3,4],[6,7],[8,9]],[[10,12],[11,13],[9,5]],[[12,12],[32,60],[11,70]]])

In [46]:
d


array([[[ 2,  2],
        [ 3,  4],
        [ 4,  5]],

       [[ 3,  4],
        [ 6,  7],
        [ 8,  9]],

       [[10, 12],
        [11, 13],
        [ 9,  5]],

       [[12, 12],
        [32, 60],
        [11, 70]]])

In [47]:
d.shape

(4, 3, 2)

In [48]:
d.sum

<function ndarray.sum>

In [49]:
d.sum(axis=1)

array([[  9,  11],
       [ 17,  20],
       [ 30,  30],
       [ 55, 142]])

In [50]:
d.sum(axis=2)

array([[ 4,  7,  9],
       [ 7, 13, 17],
       [22, 24, 14],
       [24, 92, 81]])

In [51]:
d.mean(axis=1)

array([[ 3.        ,  3.66666667],
       [ 5.66666667,  6.66666667],
       [10.        , 10.        ],
       [18.33333333, 47.33333333]])

In [52]:
c

array([[ 2,  3,  4],
       [ 3,  6,  8],
       [10, 11,  9],
       [12, 32, 11]])

In [53]:
c[0][1]

3

In [54]:
c[0:2,-1]

array([4, 8])

In [55]:
c[0:2,-1:]

array([[4],
       [8]])